sudo: required
before_install:
    - sudo add-apt-repository -y ppa:fish-shell/release-2
    - sudo apt-get update
    - sudo apt-get -y install fish
    - sudo apt-get -y install docker
script: |
    export GOPATH=~/go
    git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
    ~/.fzf/install -y
    curl -Lo ~/.config/fish/functions/fisher.fish --create-dirs git.io/fisher
    fish -c "fisher fishtape .; fishtape test/*.fish"

